# Generated by Django 3.2.8 on 2021-11-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_administrador', models.CharField(max_length=13, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('num_cel', models.BigIntegerField(unique=True)),
                ('email_personal', models.CharField(max_length=25, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_nac', models.CharField(blank=True, max_length=20, null=True)),
                ('email_empresa', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AudAdmin',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'aud_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AudCargo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'aud_cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AudCasos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'aud_casos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AudEvaluado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'aud_evaluado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AudEvaluador',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'aud_evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detalle_cargo', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id_caso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion_caso', models.CharField(max_length=500)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('pdf', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'casos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id_error', models.FloatField(primary_key=True, serialize=False)),
                ('codigo_error', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion_error', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'errores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCaso',
            fields=[
                ('id_evcaso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('video_respuesta', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'evaluacion_caso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluado',
            fields=[
                ('id_evaluado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_evaluado', models.CharField(max_length=13)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('num_cel', models.BigIntegerField(unique=True)),
                ('email_personal', models.CharField(max_length=25)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_nac', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(max_length=50)),
                ('email_empresa', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'evaluado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id_evaluador', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_evaluador', models.CharField(max_length=13, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('num_cel', models.BigIntegerField(unique=True)),
                ('email_personal', models.CharField(max_length=25, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fec_nac', models.CharField(blank=True, max_length=20, null=True)),
                ('email_empresa', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_revision', models.DateField()),
            ],
            options={
                'db_table': 'resultado',
                'managed': False,
            },
        ),
    ]
